- apt:
  - openssh-server
  - net-tools
  - build-essential
  - git
  - git-lfs
  - tree
  - tldr
  - tmux
  - screen
  - coreutils
  - moreutils
  - findutils
  - wget
  - imagemagick
  - ffmpeg
  - mosh
  - pandoc
  - poppler-utils